### ISSUE TITLE
Remove passwords

### ISSUE THREAD

**Issue by MarinusVanDijk** [CBSMicroData/kansrijke_start_analysis#3]
I saw a password in the R file where the database is accessed.

Perhaps remove it?

**Comment by schreudera** [comment]
> I saw a password in the R file where the database is accessed.
> 
> Perhaps remove it?

Yes, we should probably remove it when we prepare the files for export; I will do this for the R files in the Richard Anton folder.

**Comment by MarinusVanDijk** [comment]
The password is currently in this repository!
